### ISSUE TITLE
Nothing seems to be rounded "by default?"

### ISSUE THREAD

**Issue by dorkbuttt** [Androser420/sysmol24#2]
Using base Discord with Vencord injected and inserting the theme into the Online Themes settings section.

**Comment by Androser420** [comment]
hey sorry lol for some reason i decided to make the default theme an exception when it comes to rounding back then 😅
i was thinking of making it closer to original by doing that so others dont have to add unrounding.css manually, but now i see that just limits it more
https://github.com/Androser420/sysmol24/commit/4840fae2e51720b23c60475f254f72e13c3e1ef5
thanks for the reminder!
